version: '3.8'

services:
  # Open WebUI服务 (容器化)
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8888:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WEBUI_SECRET_KEY=your-secret-key-here
    volumes:
      - open-webui:/app/backend/data
      # 挂载整个静态文件目录
      - ./static:/app/backend/static/custom
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  open-webui:

# 注意: 语音助手API现在在主机上运行
# 启动命令: python voice_api_server_optimized.py
# 或使用容器化版本: docker-compose -f docker-compose-full.yml up